# CodeChat Configuration File
# API keys should be set as environment variables (PINECONE_API_KEY, OPENAI_API_KEY, GOOGLE_API_KEY)
# This file contains non-sensitive configuration settings.

[pinecone]
environment = "us-east-1-aws"
index = "model-earth-jam-stack"
namespace = "codechat-main"

[openai]
model = "text-embedding-3-small"
dimensions = 1536

[chunking]
max_chunk_size = 1000
overlap_size = 100
max_workers = 4
batch_size = 100

[ingestion]
processing_mode = "local"  # "local" or "lambda"
verbose = true
default_config_file = "config/modelearth_repos.yml"

# AWS Configuration (only needed for Lambda mode)
[aws]
region = "us-east-1"
# sqs_queue_url = "https://sqs.us-east-1.amazonaws.com/account/queue-name"
# s3_archive_bucket = "codechat-vector-archives-account"

# Note: Set these as environment variables, not in this file:
# OPENAI_API_KEY=your-openai-key
# PINECONE_API_KEY=your-pinecone-key
# PINECONE_ENVIRONMENT=us-east-1-aws
# PINECONE_INDEX_NAME=your-index-name
# S3_BUCKET=your-bucket-name
